create table if not exists public.contact_us (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  "isRead" boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_contact_us_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_contact_us_updated_at on public.contact_us;

create trigger set_contact_us_updated_at
before update on public.contact_us
for each row
execute function public.set_contact_us_updated_at();
